## bms_business

CREATE DATABASE `bms_business`;

CREATE TABLE `bms_store` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '自增店铺ID',
  `name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '店铺名称',
  `created_at` DATETIME NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '记录更新时间',
  `deleted_at` DATETIME NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '记录删除时间',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '店铺状态',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB CHARSET=utf8mb4 COMMENT='存储店铺';

CREATE TABLE `bms_business` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '自增商家ID',
  `store_id` BIGINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '店铺ID',
  `nick_name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '账号昵称',
  `icon` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '头像',
  `created_at` DATETIME NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '记录更新时间',
  `deleted_at` DATETIME NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '记录删除时间',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '账号状态',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB CHARSET=utf8mb4 COMMENT='存储账号';

CREATE TABLE `bms_business_authentication` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '自增ID',
  `business_id` BIGINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '账号ID',
  `identity_type` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '登录类型',
  `identifier` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '登录标识',
  `credential` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '密码凭证',
  `created_at` DATETIME NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '记录更新时间',
  `deleted_at` DATETIME NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '记录删除时间',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '账号状态',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB CHARSET=utf8mb4 COMMENT='存储账号认证信息';

CREATE TABLE `bms_business_authorization` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '自增ID',
  `business_id` BIGINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '商家ID',
  `role` TINYINT UNSIGNED NOT NULL DEFAULT '0' COMMENT '账号角色',
  `authority` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '账号权限',
  `created_at` DATETIME NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '记录更新时间',
  `deleted_at` DATETIME NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '记录删除时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB CHARSET=utf8mb4 COMMENT='存储账号授权信息';